# Generated by Django 4.2.30 on 2026-05-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='attendance_student_5b1d70_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['timestamp'], name='attendance_timesta_d0ec2c_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['student'], name='embeddings_student_a43def_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['created_date'], name='embeddings_created_6f8a74_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='students_name_ead02e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['active'], name='students_active_005329_idx'),
        ),
    ]
