# Generated by Django 4.2.30 on 2026-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='photo_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash de la photo pour détecter les doublons', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='enrollment_photo_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
